### ISSUE TITLE
Format validation should succeed if the type of the instance is invalid

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1188]
See https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.1

Basically it means let `type` to validate the type of the instance.

**Comment by kiootic** [comment]
It turns out the upstream JSON schema validator does not conform to it, and the test suite they used is outdated and does not include the [relevant test cases](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/95425df4f60c1e001a39e4988a7abd85f2bd2caf/tests/draft4/format.json).

Additionally, due to bugs in test code, some test cases are actually ignored.

**Comment by louischan-oursky** [comment]
Let's remove the bundled formats and add a comment to explain why they are removed.

**Comment by louischan-oursky** [comment]
Per our offline discussion, we are going to update the fork to make bundled formats conform to the spec.
