### ISSUE TITLE
iOT project (raspberry pi 2 / 3) Scaffolding

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-server#135]

**Comment by royuen** [comment]
Discussion 5 Sept
- Sign up => sign up with username, with username as device's identifier / uuid, password as hard code / mac address / uuid / etc
- Assume node.js application
- Review if we should integrate with those platform's famous JS framework, it is because they should need to fetch some values from the hardware and pass it to skygear
- Scaffolding should be able to generate ardunio / RasPi3 project

**Comment by royuen** [comment]
Updates:
- Support raspberry pi 2 / 3
- OS suggests https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2 / https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3
- Node.js example project with skygear loaded
- Readme with instruction for deployment steps, files to change, etc.

**Comment by royuen** [comment]
https://github.com/skygear-demo/raspberrypi-example

**Comment by rickmak** [comment]
Latest code pushed to the repos, feel free to leave comment and open issue there.
