### ISSUE TITLE
`make test` is not working when WITH_DOCKER it set

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#157]
The provided `DOCKER_RUN` is not working since it don't boot postgresql and redis for testing

- Skygear Server Date/Version: v0.17.0
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results

Test passed

#### Actual Results

various `dial tcp 127.0.0.1:6379: getsockopt: connection refused` and `Unable to begin transaction for schema migration: dial tcp [::1]:5432: getsockopt: connection refused`  indicate the test is fails.

#### Steps to reproduce

1. WITH_DOCKER=1 make test

**Comment by cheungpat** [comment]
Probably need to use docker-compose for the test to succeed, but docker-compose isn’t need for building the binary, so we either run docker-compose for all steps (which I don’t like, because that is unnecessary) or we provide `WITH_DOCKER_COMPOSE=1` for that purpose.

I run test case in Docker using Docker Compose, but I run the command manually rather than using `Makefile`.

**Comment by rickmak** [comment]
I think it will be ok to using `docker-compose` to run test when `WITH_DOCKER=1`. Something like this?

```
ifeq (1,${WITH_DOCKER})
DOCKER_RUN := docker run xxxxx
DOCKER__COMPOSE_RUN := docker-compose xxxx
endif
```
