### ISSUE TITLE
Sanitize log output for sensitive information

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#220]
Since people will be posting their log for debug, it is better if we sanitize the log output for hiding sensitive information (such as access token, api key, master key and password) to protect their personal data.

**Comment by tensiuyan** [comment]
note: we need a full list of sensitive information

**Comment by kaojohnny** [comment]
https://oursky.quip.com/1rezANjuu4Yt

**Comment by chpapa** [comment]
@kaojohnny thanks for putting the list and plan together!

A reminder is I think it might be better for the document to be on Github as comment (or a spec in skygeario/feature) because it is suppose to be an open source project (mostly sponsor by Oursky lol) we should try to keep information to public instead of private document within Oursky Quip.

I know we have been doing quite a lot of it for NEXT refactor, so it is just a reminder for all of us to beware of what should live in opensource and what should be in the company.
