### ISSUE TITLE
AWS CloudFormation Skygear template use

### ISSUE THREAD

**Issue by dauletico** [SkygearIO/skygear-server#269]
I have used Skygear template for AWS Cloudformation to deploy skygear on aws.
Template is working perfect. After that I follow your server installation guidance for Fabric installation and etc.

When I try to run command in myapp/ directory "fab -H ubuntu@127.0.0.1 restart" or any other command I receive password prompt for ubuntu user. AWS do not allow to set passwords for ec2 linux users, only keys.
What should I do?

**Comment by dauletico** [comment]
added private pem file with fab -i command and it stopped to prompt password.
All commands now work but skygear-server do not start
curl http://127.0.0.1:3000
curl: (56) Recv failure: Connection reset by peer

**Comment by dauletico** [comment]
docker-compose up server
Creating volume "myapp_db_data" with local driver
Creating volume "myapp_redis_data" with local driver
Creating volume "myapp_server_data" with local driver
Starting myapp_server_1
Attaching to myapp_server_1
server_1 | 2017/01/20 20:41:14 Error in loading .env file
server_1 | API_KEY is not set
myapp_server_1 exited with code 0

what is .env file? where should it be placed and content?

**Comment by chpapa** [comment]
@dauletico Sorry about the problem, it was because the AWS CloudFormation template was out of date :( We're updating a new guide for deployment without docker, please stay tuned at our [Google group](https://groups.google.com/forum/#!forum/skygear-user-group) for updates in next two weeks. Meanwhile please try it out with our free development plan first on [Skygear.io](https://Skygear.io)?
