### ISSUE TITLE
Bidirectional plugin transport and multiplexing

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#295]
- [x] [Golang] Try to send a dummy message after a new request, before receiving the response 
- [x] [Python] Try to catch that message
- [x] [Python] Look at the normal http transport
- [x] [Python] Send request via zmq
- [x] [Golang] Handle that request
  - [x] Create fake http request from zmq request
  - [x] Inject into http server
- [x] [Golang] Send back the worker id in response
- [x] [Python] Ask the worker to handle the response
- [x] [Golang] Handle worker-reuse when a worker is calling itself
- [x] [Golang] Support multiple plugins
- [x] [Golang] Add a stack count
  - [x] Set a maximum and throw error when exceeded 

---

The current plugin transport only support communication initiated from the server side of the transport. 

There is an existing mechanism for the plugin to make request to the server just like a normal client by making http request through request router. This mechanism is often referred to as `send_action` named after the python function with the same name.

It is proposed that we should implement bidirectional plugin transport so that plugin-initiated request are made through the plugin transport instead. Multiplexing refers to how transport route communication among workers.

## Benefits for implementing bidirectional plugin transport and multiplexing

* easier configuration - while transport may require extra config for bidirectional communication, no config is necessary for api key, master key and server endpoint.
* reduced overhead - imitating a client request requires the plugin to make extra http connection, which is extra overhead when using zmq transport.
* tracking request lifecycle - keep track of control flow across process boundary (to support better logging).
* reuse blocked workers - control flow can be handed off to the blocked worker if the blocked worker is handling the same request.

## Implementation approach

* (existing behavior) plugin runtime register a new worker for each thread
* transport keep track of context when sending message across process boundary
* transport to increment call stack when crossing process boundary
* when call-stack=0, select a free worker from pool, worker is no longer in the pool for other requests
* call-stack++ and send message to worker
* worker may call server code (new behavior), two options here (see below)
* call-stack++ when receiving message from worker that will call other server code
* when call-stack=2, re-use the same worker previously selected, use request unique ID to find the worker
* when plugin code returns data (i.e. not calling other server code) call-stack is decremented
* when call-stack=0, the worker is marked free and put back to pool

### ZMQ Transport protocol options

Option 1: Overload the current ZMQ transport protocol design in that plugin code calls server code by using the response message, the server code returns data by using the request message.

This option is less intrusive to the overall ZMQ transport protocol design. The semantic maybe convoluted.

Option 2: Add a new kind of message in the ZMQ transport protocol design so that plugin code calls server code by using a new kind of request message, and the server code returns data by using a new kind of response message.

The semantic is easier to understand.

### HTTP Transport protocol options

We have to decide whether multiplexing makes sense in HTTP transport, this is because send_action is inherently HTTP-based.

If we want HTTP transport to support multiplexing, the transport will expose a http endpoint for the plugin to call server-side code.

**Comment by cheungpat** [comment]
@b123400 thanks for coming up with a list, i couldn’t have came up with the list myself

but i think we need to talk about it so we are on the same page

I’d like to address this specific point:

> Embed HTTP request body into zmq message, with worker id

One of the design decision early on is that the Skygear request router is designed in a way that it does not necessarily have HTTP semantics. When we are going to implement bidirectional communication, I think we can make use of this design so that you do not need to wrap `send_action` in a HTTP request payload before sending from the plugin to the server.

**Comment by rickmak** [comment]
python call send_action
transport send message to server (return XXX)
wait
wait receive message <- send_action.result  / new call handle

**Comment by b123400** [comment]
I just finished designing the protocol between `skygear-server` and plugin, and realise it can be done without increasing the message size! Please comment / see if I have any misunderstanding of the protocol.

The [current implementation](https://github.com/SkygearIO/skygear-server/blob/4b81eab8672492c65fe024db3f061c89494f234d/pkg/server/plugin/zmq/broker.go#L251-L256) sends the identity of the worker to the worker (the same thing happens when sending response), it is not necessary as the worker already know its own identity. I replaced it with a randomly generated request_id, which would do the multiplexing.

As for the bidirectional part, since the one who send the request definitely remember it sent the request, so there is no need to add something like `type=request` or `type=response` to the message. My current implementation is something like this:
- When each side send a request to the other side, generate an unique id for the request
- Sender should remember the id
  - It can be any form of implementation
  - Golang's current implementation of `addressChan map[string]chan []byte` is already good enough
- When getting a message from socket, check if that is a new id
  - If it is a new id, that means the remote created the message, it is a request
  - otherwise, it is a response
- When a request is received, they have to send a response with the same request id

With this design, the message size can remain the same (which is not necessary, but I find this elegant).
Drawback I can think of:
- More difficult to debug because you cannot know whether a message is request/response just by intercepting the traffic
- Difficult to understand?

**Comment by chpapa** [comment]
Disclaimer: I have no idea how the whole things work, so I maybe speaking something crazy...

My high-level business understanding to the problem was these (which seems not mentioned in the description or write it in a technical way which I have difficulties to comprehend):

- avoid the worker exhaust problem, so send_action generated from the worker goes to the same worker.
- so that we can timeout a request (already done?) for infinity loop of send_action or deadlock of external resources
- track requests for better logging in future

Are these kind of included or they are different things?

**Comment by chpapa** [comment]
Disclaimer: I may have no idea what I am talking about 

The new protocol and design seems assume when funcA is calling funcB, it is a sync request. If in future we want to support async send_action, does the current protocol works? Or that should be an independent request and won't be considered here?

(If I am non-sense feel free to ignore the message)

**Comment by rickmak** [comment]
RE @b123400, in your design. You took two assumption which is not true. 1. There is only one instance of python process connect to `skygear-server`. 2. The call is always within same Plugin type.

> Golang's current implementation of addressChan map[string]chan []byte is already good enough

You are overloading the semantic of this map which is not recommended. You can reuse this map because you take the assumption 1.


> When getting a message from socket, check if that is a new id
If it is a new id, that means the remote created the id, it is a request
otherwise, it is a response

Don't take implicit logic to determine it is request or response. Make it explicit hence debuggable.

Can we have a data flow next time when you come up with a new transport format. It will help discussion.

**Comment by rickmak** [comment]
RE @chpapa 

> avoid the worker exhaust problem, so send_action generated from the worker goes to the same worker.
Yes, it is the main objective.

> so that we can timeout a request (already done?) for infinity loop of send_action or deadlock of external resources
- timeout already inplace.
- infinity loop can be prevent after we introduce something like `bounce_count `, it is not the main objective of this issue.

> track requests for better logging in future
- We plan to have `request_id` and `bounce_count`. I will help better logging. Again, it is not the main objective of this issue.

**Comment by rickmak** [comment]
> The new protocol and design seems assume when funcA is calling funcB, it is a sync request. If in future we want to support async send_action, does the current protocol works? Or that should be an independent request and won't be considered here?

You raise a good question. The protocol assume sync func call. We don't consider remove the assumption of sync properties of worker in protocol level.

Initial plan for support async worker will be worker responsibility to dynamic register as many sync worker. Say JS will regards itself as 20 (configurable?) sync worker. Or JS can register dynamically. More ideal on this is welcome.

**Comment by b123400** [comment]
Ok, after revising the above concerns, I propose the following protocol:

The current message in ZMQ is: `[address-stacak]|0|message`
For example: `address2|address1|0|message`

The updated message will be `[address-stack]|0|[request-stack]|0|message-type|bounce_count|message`
For example: `address-2|address-1|0|request-id2|request-id1|0|message_type|bounce_count|message`

where 

- `message_type` is either `REQ` or `RES`,
- `bounce_count` is an integer start from 0, every time a server send a request / response, it will increase by 1

Every time a new request is made, a worker-id has to be added to the `address-stack`, even when they are the same worker. This is to manage requests between multiple plugins. Therefore, the length of address-id stack and request-id stack should always be the same.

_In the following examples, the message does not really matter, I just make them up_

# Case 1, simple call from server to plugin:

server sends request: 

`worker-id|0|request-id|0|REQ|0|{"lambda":"..."}`

client sends back response:

`worker-id|0|request-id|0|RES|1|{"lambda-result":{}}`

# Case 2, plugin calls server during request

server sends request:

`worker-id|0|request-id1|0|REQ|0|{"lambda":"..."}`

client sends request:

`worker-id|worker-id|0|request-id2|request-id1|0|REQ|1|{"query":"..."}`

server sends response:

`worker-id|worker-id|0|request-id2|request-id1|0|RES|2|{"results":[]}`

client sends response:

`worker-id|0|request-id1|0|RES|3|{"lambda-result":{}}`

# Case 3, plugin calls another plugin

Plugin A sends request to server:

`worker-id-A|0|request-id1|0|REQ|0|{"plugin-b-lambda":"..."}`

Server calls pluginB:

`worker-id-B|worker-id-A|0|requestid-2|request-id1|0|REQ|1|{"plugin-b-lambda":"..."}`

Plugin B responses to server:

`worker-id-B|worker-id-A|0|requestid-2|request-id1|0|RES|1|{"plugin-b-result":""}`

Server responses to plugin A:

`worker-id-A|0|request-id1|0|RES|1|{"plugin-b-result":""}`

# Async worker
I agree Rick's way of implementing async worker, JS can register itself as multiple workers, and can manage tasks with async style internally. More modification is needed to support dynamic number of workers, probably updating the ready event, but it will not be covered in this PR.

**Comment by rickmak** [comment]
@b123400 please try to keep the discussed point in github issue. So we can refer back in future. 

As the summary of Skype meeting on 21 Feb 2017. Follow topic is covered and clarify.

1. The middle part, i.e. `request_id`, `type` and `bounce_count`. and the last part. Should be separate by `0` separator. To represent it is belong to different level of abstraction.
1. The order of the message in protocol it not arbitrary. We agreed on two rule. First, fixed length come first. Second, important come first. It will affect on weather we need to parse the whole message when making routing decision.
1. json is an acceptable implementation if we can lack of time and data to decide a good binary format.
1. We are solving resource problem of sequential call between server and plugin. Not parallel call of plugin. i.e. 100 non dependent after_save.

My proposed format alteration is:

[address-stack]|0|[request-info]|0|[application-payload]

With

__request info__

|type|bounce_count|request_id|

example
|REQ|1|Z7SD-SHDK|

Follow should be true
1. request_id is fixed length.
2. type is fixed length.
3. combination of type, bounce_count and request_id can uniquely identify the request.

In REQ, the bounce_count will increment. In RES, the bounce_count will decrement.

request_id consist two parts 0x10000. Prefix is the request ID visible to skygear enduser. Suffix is for plugin-server request. Idea come from https://github.com/SkygearIO/py-skygear/blob/master/skygear/transmitter/zmq.py#L54

Hope we are on the same page.

**Comment by b123400** [comment]
@rickmak I actually updated above the comment to reflect the conclusion from discussion, because I don't want to read the entire thread to understand the protocol, but if you prefer a new comment, sure.

I think the conclusion we came up in discussion is quite different from what you are proposing, but I will just follow yours. So here is the revised protocol:

------------

The current message in ZMQ is: `[address-stacak]|0|message`
For example: `address2|address1|0|message`

The updated message will be `[address-stack]|0|[request-info]|0|message`
For example: `address-2|address-1|0|type|bounce_count|request-id|0|message`

In request-info:

- `request_id` is a uuid for the request
- `type` is either `REQ` or `RES`
- `bounce_count` is an integer start from 0, every time a request is sent, it will increase by 1, every time a response is received, it will decrease by 1.

Every time a new request is made, a worker-id has to be added to the `address-stack`, even when they are the same worker. This is to manage requests between multiple plugins.

_In the following examples, the message does not really matter, I just make them up_

# Case 1, simple call from server to plugin:

server sends request: 

`worker-id|0|REQ|0|request-id|0|{"lambda":"..."}`

plugin sends back response:

`worker-id|0|RES|0|request-id|0|{"lambda-result":{}}`

# Case 2, plugin calls server during request

server sends request:

`worker-id|0|REQ|0|request-id|0||{"lambda":"..."}`

plugin sends request:

`worker-id|worker-id|0|REQ|1|request-id|0|{"query":"..."}`

server sends response:

`worker-id|worker-id|0|RES|1|request-id|0|{"results":[]}`

plugin sends response:

`worker-id|0|RES|0|request-id|0|{"lambda-result":{}}`

# Case 3, plugin calls another plugin

Plugin A sends request to server:

`worker-id-A|0|REQ|0|request-id|0|{"plugin-b-lambda":"..."}`

Server calls pluginB:

`worker-id-B|worker-id-A|REQ|1|request-id|0|{"plugin-b-lambda":"..."}`

Plugin B responses to server:

`worker-id-B|worker-id-A|0|RES|1|request-id|0|{"plugin-b-result":""}`

Server responses to plugin A:

`worker-id-A|0|RES|0|request-id|0|{"plugin-b-result":""}`

# Multiple requests and request id

When there are multiple independent requests, each of them will have their own request id. For example 100 calls of before save will have 100 different request id, because they are not dependent (not nested).

# Async worker
I agree Rick's way of implementing async worker, JS can register itself as multiple workers, and can manage tasks with async style internally. More modification is needed to support dynamic number of workers, probably updating the ready event, but it will not be covered in this PR.

**Comment by b123400** [comment]
I have an issue want to discuss during standup, post it now so in case if someone like to think about it first.

In `py-skygear`, SkygearContainer is completely based on sending HTTP requests, I think it is not very good to add behaviour of sending request via zmq in the same class. Do you think I should create a new class and expect users to use it? Or just reuse the same class, and "smartly" detect the transport, then ignore all those `endpoint`, `api_key`, `access_token` attributes? or any other design?

I think this is a question of code beauty vs convenience, which I have no opinion, and no idea what is it like in this project

**Comment by cheungpat** [comment]
> Or just reuse the same class, and "smartly" detect the transport

I assume you are talking about SkygearContainer and the `send_action` methods. If you aren’t, throw the following comments away:

I think yes. because the only reason the user will call `send_action` is when the user wants to call an action provided by skygear (or one of the plugins). The original design is to send the action through the transport, but we end up implementing just HTTP and through the HTTP endpoint.

The current SkygearContainer design is not good anyway, because we need master key etc which is not really needed if we go through the ZMQ transport (which is guaranteed to come from a plugin).

If you are talking about retaining old behaviour so that people wouldn’t be surprised if they rely on transport behavior, I am okay with adding new function so that the original send_action will do things the old fashioned way.

**Comment by b123400** [comment]
Ok. I am more concerning about the actual code written. Currently user only has one way to create SkygearContainer, but in the future it will be something like this:

```
// if you are using HTTP transport:
SkygearContainer(endpoint=..., access_token=..., api_key=...)
// if you are using ZMQ:
SkygearContainer()
```

Which means when we want to change the transport, we cannot just change an environment variable (from `CATAPI_TRANSPORT=http` to `CATAPI_TRANSPORT=zmq`), we also need to update code.

**Comment by b123400** [comment]
When I was developing address-stack, I found an issue with the address stack design and decided to try another method.

# Issue with the original design

PluginA code:
```
@op('foo:hello')
def english():
    send_action('foo:ciao')
    return {'key':'thanks'}
```

PluginB code:
```
@op('foo:ciao')
def italian():
    return {'key':'grazie'}
```
Would results in:
1. Browser calls /foo/hello
2. Server calls pluginA with address-stack [A]
3. PluginA calls server with address-stack [A]
4. Server calls pluginB with address-stack [A, B]
5. PluginB responses server with with address-stack [A, B]
6. Server responses pluginA with with address-stack [A]
7. PluginA responses server with with address-stack [A]

The problem occurs in between step 5 and 6. When server receives the responses from pluginB with the stack [A, B], after popping B, it has access to worker-id of A, it is the worker the server should send response to (as in 6). However, only knowing the worker-id is not enough, the server also has to know which plugin to send to. Looping through all the plugins to find the one with that worker-id does not seems to be a good idea too. We can maintain a stack of channels, such that the server will be able to response without knowing which plugin (or even the worker-id), but I came up with a solution that has more benefit.

# The updated solution

Instead of maintaining the worker-id in address-stack, we remember "which worker-id is used for this plugin for this request" in the server. There would be a (per request) map of "plugin-id to worker-id", basically say "If I want to send message to this plugin, this is the worker to use". For example:
1. Browser calls /foo/hello
2. Server calls pluginA with worker-id A, the map is now `{"pluginA":"A"}`
3. PluginA calls server
4. Server calls pluginB with worker-id B, the map is now `{"pluginA":"A", "pluginB":"B"}`
5. PluginB responses server
6. Server looks at the map, decided A is the correct worker-id to send to pluginA
7. PluginA responses server with with address-stack [A]

This design also has a benefit, when A calls B, and B calls A, the server will be able to reuse the same worker, which the stack implementation cannot do.

**Comment by rickmak** [comment]
I agree your updated solution.

One additional question:
Did you ever consider there is transport other than ZMQ?

i.e. plugin A can be ZMQ and plugin B can be HTTP.

My idea will be let the `Router` to find out with transport instance is responsible for handling the request.

So all `send_action` will still go through the `Router` path. The broker in ZMQ will try to reuse the worker by maintaining a request ID to worker map.

We need to make sure the HTTP transport will not surprise by the new request info.

**Comment by b123400** [comment]
> Did you ever consider there is transport other than ZMQ?

Yes. I have tested it with the both following setups, they run perfectly:
- Plugin A(ZMQ) calls Plugin B (HTTP) calls Plugin A (ZMQ)
- Plugin A(HTTP) calls Plugin B (ZMQ) calls Plugin A (HTTP)

-----

I am getting quite confused by "let the Router to find out which transport instance is responsible for handling the request." (I assume you mean "which" instead of "with")

- By "request", I assume you mean a request received on `skygear-server`, such as `schema/fetch` or `catapi/get`. (We have lots of requests going on, it will be better to specify what request is it, from where / to where)
- I didn't modify the "router to transport" path. Does that satisfy "let the Router to find out which transport instance is responsible for handling the request"?
- To implement bidirectional transport, I did the following things:
  - Make router accepts payload (via `HandlePayload`), instead of raw HTTP Request
  - Implement the old `ServeHTTP` using the above `HandlePayload`
  - Extend the payload type to contain method and path
    - This is because I think the current router and handler is fundamentally http dependent, see below.
  - When plugin sends request to `skygear-server`:
    - A payload is created
    - The payload is passed to `router.HandlerPayload`, the same function as every other HTTP request 

-----

# Relationship between HTTP and router/handlers

From what I observe in code, the current router and handlers are heavily HTTP dependent. Therefore I decided to make the Payload more HTTP-alike instead of refactor it.

- [router.Response depends on http.ResponseWriter for getting response](https://github.com/SkygearIO/skygear-server/blob/abad0024201cdce81a091e379f8759405836b29e/pkg/server/router/model.go#L160)
- [Handlers clearly understand response is a HTTP response, instead of something generic](https://github.com/SkygearIO/skygear-server/blob/abad0024201cdce81a091e379f8759405836b29e/pkg/server/handler/file.go#L135)
- [router.NewGateway depends on the concept of path, which is HTTP specific](https://github.com/SkygearIO/skygear-server/blob/abad0024201cdce81a091e379f8759405836b29e/pkg/server/router/gateway.go#L39)
  - Gateway is said to be HTTP only, but the current architecture of "gateway serves request via the `commonRouter` interface" forces the `commonRouter` interface to have knowledge of path.

**Comment by rickmak** [comment]
> From what I observe in code, the current router and handlers are heavily HTTP dependent. Therefore I decided to make the Payload more HTTP-alike instead of refactor it.

Short answer: idea and reality. Don't give up our dream.
