### ISSUE TITLE
DEV_MODE behaviour is inconsistent with integer type column

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#319]
`DEV_MODE` behaviour is inconsistent.

- Skygear Server Date/Version: v0.22.1
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Steps to reproduce

1. Create a skygear-like table with one column set to postgresql data type `integer`
2. Use sdk api `save` to save a record.

#### Actual Results
When `DEV_MODE=YES`, saving to a table containing `integer` column is fine and the column does **NOT** auto migrate to `double precision`.
When `DEV_MODE=NO`, skygear server complains it cannot perform migration.

#### Expected Results
I think skygear-server should complain that `integer` is never a supported data type regardless of `DEV_MODE` is on or off.

**Comment by cheungpat** [comment]
I think the desired result should be that when the column has `integer` type, the following should happens, regardless of `DEV_MODE` settings:

* when saving a record with field value that can be interpreted as integer without losing precision, saving should be successful
* otherwise, the saving should result in an error (probably incompatible schema/data type (forgot the actual name))

**Comment by cheungpat** [comment]
On the other hand, I am guessing what @louischan-oursky meant when he said the behaviour is inconsistent. I haven’t looked at the code yet, but I suppose that when `DEV_MODE=NO`, `integer` is considered incompatible with `double precision` while when `DEV_MODE=YES`, it is considered compatible. We could probably improve the compatibility check.
