### ISSUE TITLE
Field-based ACL behaviour

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/skygear-server#479]
Discussed with @rickmak and @ben181231 offline, there seems to be some mis-alignment on the behaviour of how the field-based ACL works. The discussion is based on the following scenario:

This is how the current v1.1.0 skygear-server works.

I am NOT logged in to the server, and I want to query user by user.username.

Initially, the field ACL setting of ALL record types is:

record|field|user role|access|discovery
---|---|---|---|---
user|username|owner|read write|queryable
user|username|public|no access|not queryable

Then when I query user by user.username, I would get error.

Now I delete the public one, the field ACL setting is:

record|field|user role|access|discovery
---|---|---|---|---
user|username|owner|read write|queryable

**So if I query user by user.username, will I still get the error?**

There are two side of opinions.

## 1

There are three levels of field ACL the server need to match:

1. `user.username`
1. `user.*`
1. `*.*`

Since an entry is found for the first condition, the server will match by that entry. The entries are worked by whitelist. So only owner can query by user.username, others will get error.

Result: Error, so having the `Public` entry or not DOES NOT affect the result

## 2

On top of the above three conditions, the server will also match the user role. So effectively the server will try to find entries that match `user.username` **AND** user role that can match not authenticated user.

Then no entries are matched. The default behaviour will be applied.

Result: Query successfully, so the `Public` entry DOES affect the result

---

The actual result is **2**.

#### Why there is such a discussion

There is a `Private` option in Skygear portal  schema table acl setting modal dialog. There are two entries, which are exactly the first table in the above scenario. Then after some offline discussion, we thought there should only be one entry, the `Public` one should be useless. 

But this is not correct in the current implementation.

**Comment by cheungpat** [comment]
The [current design](https://github.com/SkygearIO/features/blob/master/features/48-user-profile-discovery/field-based-acl.md) and [implementation](https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skydb/access.go) is based on a rule-baesd matching algorithm and the default for unmatched rule is least-restrictive (i.e. public readwrite, queryable, aka *full* access).

The default is least-restrictive because the field-based ACL work hand-in-hand with record ACL, and having a default for least-restrictive is consistent with existing behaviour (i.e. we don’t want to break existing app nor do we want developers to add *public full access* in order to revert to previous behaviour).

It appears the portal design assumes the server to be a whitelist mechanism. I am not in the discussion so I am not sure what is the proposed algorithm, but I guess changing the unmatched rule default to be most-restictive (i.e. no access) would fit the bill.

Changing the unmatch rule to be most-restrictive that also means the `_record_field_access` table must have a `*:*` rule for public full access to retain existing behavior. The server will have to add this rule during 1) first time init; and 2) migrating from previous version.

I am okay with this new design.

---

I also heard that there is another discussion for changing the existing algorithm such that:

* if there exists rule matching user record type and/or field, assume *no access*, unless otherwise permitted by a rule (i.e whitelist)
* if there is no rule matching user record type and/or field, then assume *full access* (i.e. permissive default)

(correct me if I am mistaken in what I heard)

The problem is: you will always have a rule that matches user record type and/or field, because we have wildcard rule `*:*`. If we have such rule, the first point above always apply.

(once again if this is not the algorithm you are talking about, let me know what it is, sorry I am not in the offline discussion)

Example:

record|field|user role|access|discovery
---|---|---|---|---
user|username|owner|read write|queryable
user|username|any user|no access|not queryable
user|*|public|read only|queryable

In this situation, public has read only, queryable access to `user:username` because of `user:*` rule matching. In the portal UI, the portal will only shows the first two rules, meaning that the developer may not be aware that the third rule exists and will apply to public.

Therefore, to make the rules explicit in the UI, the developer should set this. Alternatively, the portal UI can display the rule above while configuring the server with rules below:

record|field|user role|access|discovery
---|---|---|---|---
user|username|owner|read write|queryable
user|username|any user|no access|not queryable
user|username|public|no access|not queryable
user|*|public|read only|queryable

---

I hope this makes sense?

**Comment by carmenlau** [comment]
@rickmak Would like to confirm with you to deploy the changes to staging. Just tested and found still be able to get the fields after I changed the field to private. Thanks!
