### ISSUE TITLE
Record save handler

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-server#708]

**Comment by Steven-Chan** [comment]
Note on some offline discussion with @rickmak and @carmenlau about naming on database table for record gears.

In v1, we have a convention that `_xxx` are skygear reserved tables and others are user defined tables.

In next, we have a convention that `_{gear}_xxx` are tables for each gear. While record gear has some reserved tables itself, thus we need to define a format to distinguish user defined tables.

The conclusion is, 
- `_record_xxx` are record gear reserved tables
- `_record__xxx` are user defined table, e.g. `_record__user`, `_record__category`, `_record__label`

**Comment by chpapa** [comment]
@Steven-Chan @rickmak @carmenlau 
Have we considered the option of anything not started with `_` are user-defined tables? So it would be simply `user`, `category`, `label` etc... I thought it is better because:

1. People directly connect to DB is easier / type a few fewer characters.
1. Avoid breaking some convention when other plugins need to access user-defined tables, that they are actually accessing the `_record` namespace.
