### ISSUE TITLE
next: SSO support auto link

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-server#889]
We had the `AutoLinkProviderKeys` config in the next code base, but the auto link feature is not implemented yet.

**Comment by louischan-oursky** [comment]
Discussed with @kiootic 

We are going to change `AutoLinkProviderKeys` to `AutoLinkEnabled` default to `false`
Same as v1 portal, we only consider `email`.

**Comment by kiootic** [comment]
Also, only allow auto-linking when allowed realms == `["default"]`

**Comment by chpapa** [comment]
> Also, only allow auto-linking when allowed realms == `["default"]`

What does "when allowed realms" meant? Is there a new configuration something like `autolink_allowed_realm` ?

**Comment by kiootic** [comment]
Allowed realm is the whitelisted realms specified by developer, specified in https://github.com/kiootic/skygear-features/blob/323-login-id/features/323-login-id/stage-1.md#configuration.

**Comment by louischan-oursky** [comment]
> What does "when allowed realms" meant? Is there a new configuration something like autolink_allowed_realm ?

No.

Auto linking happens when
1. The developer does not configure allowed realms so its value is `["default"]`
2. The email given by the identify provider match any login id of type `email` of an existing user.

The reason why we only merge when allowed realms is `["default"]` is there will be ambiguity on how to choose which existing user. Let me explain with an example.

---

Suppose the developer has configured allowed realms to be `["teacher", "student"]` and login id key `email` is of type `email`

The database has the following password principals.

UserID|LoginIDKey|LoginID|Realm
-|-|-|-
A|email|louischan@example.com|teacher
B|email|louischan@example.com|student

When an incoming SSO login has email `louischan@example.com`, we do not know which UserID `A` or `B` to associate with. In this case, a new UserID `C` is created, instead of associating the SSO login with neither `A` or `B`.

---

Alternative solution may be introducing a new configuration to allow the developer to teach us how to resolve ambiguity.

**Comment by chpapa** [comment]
@louischan-oursky If we treat same email but different realm as two users, I think it should not be a configuration to specify "auto-link to which realm", instead it should be a function call's parameter when autolink happens.

**Comment by louischan-oursky** [comment]
> instead it should be a function call's parameter when autolink happens.

I guess it should be a parameter to be provided at SDK level. We do not have a spec on SSO for next. The current implementation is ported from v1. We should properly write a spec on SSO.

**Comment by chpapa** [comment]
> I guess it should be a parameter to be provided at SDK level. We do not have a spec on SSO for next. The current implementation is ported from v1. We should properly write a spec on SSO.

Agree. Maybe just port it first and add a few features issues for things we need new spec.

Add one feature issue about supporting auto-linking with realm? Realm is something new...

**Comment by louischan-oursky** [comment]
Superseded by https://github.com/SkygearIO/skygear-server/issues/976
